[package]
name = "markup-parser"
version = "0.1.0"
authors = [" Txuritan <txuritan@protonmail.com>" ]
edition = "2021"

license = "MIT"

workspace = "../.."

[dependencies]
honeycomb.workspace = true
