[workspace]
members = [
    "aloene",
    "aloene/macros",
    "html-parser",
    "mini-html-parser",
    "opal",
    "opal/macros",
    "query",
    "query/macros",
    "varela",
    "varela/command/config",
    "varela/command/index",
    "varela/command/serve",
    "varela/common",
    "varela/format/ao3",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
