[workspace]
members = [
    "aloene",
    "aloene/macros",
    "html-parser",
    "meteors",
    "meteors/command/config",
    "meteors/command/index",
    "meteors/command/serve",
    "meteors/common",
    "meteors/format/ao3",
    "mini-html-parser",
    "opal",
    "opal/macros",
    "query",
    "query/macros",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
