[package]
name = "meteors"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

[dependencies]
chrono = { version = "0.4", default-features = false }
color-eyre = { version = "0.5", default-features = false, features = [ "track-caller" ] }
ctrlc = "3.1"
flate2 = "1.0"
lazy_static = "1.4"
log = { version = "0.4", features = [ "std" ] }
mimalloc = "0.1"
owo-colors = "1.3"
path-tree = "0.1"
pico-args = "0.4"
prost = "0.7"
rand = "0.8"
regex-automata = { version = "0.1", default-features = false }
roxmltree = { version = "0.14", features = [ "std" ] }
sailfish = "0.3"
tiny_http = "0.8"

[build-dependencies]
embed-resource = "1.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
