version: '3'

tasks:
  build-android:
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    cmds:
      - cross +nightly build -Z build-std=panic_abort,std --release --target aarch64-linux-android
  build-android-debug:
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    cmds:
      - cross +nightly build --target aarch64-linux-android

  build-windows:
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: false
    cmds:
      - cargo build -Z build-std=panic_abort,std --release --target x86_64-pc-windows-msvc

  build-tailwind:
    env:
      NODE_ENV: production
    cmds:
      - npx tailwindcss -c tailwind.config.js -i crates/varela-command-serve/assets/index.css -o crates/varela-command-serve/assets/dist/index.css --minify

  viz-deps:
    cmds:
      - cargo depgraph --all-deps --dedup-transitive-deps | dot -Tpng > deps.png
