[package]
name = "xtask"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

workspace = ".."

[dependencies]
opal = { path = "../opal" }

csv = "1.1"
serde = { version = "1.0", features = [ "derive" ] }
