[package]
name = "opal-macros"
version = "0.1.0"
authors = [" Txuritan <txuritan@protonmail.com>" ]
edition = "2021"

license = "MIT"

workspace = "../.."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
venial = "0.3.0"
