[package]
name = "query"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

workspace = ".."

[dependencies]
anyhow = "1.0"
html_parser = { path = "../html-parser" }
query-macros = { path = "../query-macros" }
