[package]
name = "meteors-command-serve"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT"

workspace = ".."

[dependencies]
common = { path = "../meteors-common", package = "meteors-common" }
opal = { path = "../opal" }

argh = "0.1"
chrono = { version = "0.4", default-features = false }
ctrlc = "3.1"
form_urlencoded = "1.0"
path-tree = "0.1"
percent-encoding = "2.1"
qstring = "0.7"
tiny_http = "0.8"
