[package]
name = "meteors"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

workspace = ".."

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", default-features = false }
ctrlc = "3.1"
flate2 = "1.0"
html_parser = { path = "../html-parser" }
lazy_static = "1.4"
log = { version = "0.4", features = [ "std" ] }
mimalloc = { version = "0.1", optional = true }
owo-colors = "1.3"
path-tree = "0.1"
prost = "0.7"
qstring = "0.7"
query = { path = "../query" }
rand = "0.8"
regex-automata = { version = "0.1", default-features = false }
roxmltree = { version = "0.14", features = [ "std" ] }
sailfish = "0.3"
tiny_http = "0.8"
# url = "2.2"
xxhash-rust = { version = "0.8", features = [ "xxh3" ] }

[build-dependencies]
embed-resource = "1.3"
